
  name: Deploy VitePress site to Pages

  on:
    push:
      branches: [master]

    # 允许您从 Actions 选项卡手动运行此工作流程
    workflow_dispatch:

  # 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
  permissions:
    contents: read
    pages: write
    id-token: write

  concurrency:
    group: pages
    cancel-in-progress: false

  jobs:
    # 构建工作
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
        - uses: pnpm/action-setup@7.5.0
        # - run: npm install pnpm@7.5.0 -g
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: pnpm
        # - run: npm install pnpm@7.5.0 -g
        - name: Setup Pages
          uses: actions/configure-pages@v3
        - name: Install dependencies
          run: pnpm install
        - name: Build with VitePress
          run: |
            pnpm build
            touch docs/.vitepress/dist/.nojekyll
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
          with:
            path: docs/.vitepress/dist

    # 部署工作
    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      needs: build
      runs-on: ubuntu-latest
      name: Deploy
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2

